---
- name: get cme
  git:
    repo: https://github.com/byt3bl33d3r/CrackMapExec
    dest: /opt/cme
    update: yes
    track_submodules: yes
    recursive: yes

- name: install cme
  shell: python setup.py install
  args:
    chdir: /opt/cme