---

- name: get proxychains-ng
  git:
    repo: https://github.com/rofl0r/proxychains-ng
    dest: /opt/proxychains-ng
    update: yes

- name: install proxychains-ng
  shell: ./configure --prefix=/usr --sysconfdir=/etc && make && make install && make install-config
  args:
    chdir: /opt/proxychains-ng
