---
- name: pentest build playbook
  hosts: all
  remote_user: root
  roles:
    - common
    - { role: geerlingguy.ruby }
    - { role: naftulikay.go-dev,
        go_user: root,
        go_version: 1.21
      }
    - terminal
    - python
    - pentest/exploitation
    - pentest/intel-gathering
    - pentest/post-exploitation
    - pentest/powershell
    - pentest/vuln-analysis
    - pentest/wireless
    - pentest
