---
- name: pentest build playbook
  hosts: lab
  remote_user: root

  roles:
    - common
    - role: geerlingguy.ruby
    - terminal
    - python
    - pentest/exploitation
    - pentest/intel-gathering
    - pentest/post-exploitation
    - pentest/powershell
    - pentest/vuln-analysis
    - pentest/wireless
    - pentest
