---
- name: install python-related packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3 
    - python3-pip
    - python3-dev
    - python3-distutils
    - python3-venv

- name: install pip3 packages
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
  with_items:
    - pacu 
    - requests
    - virtualenv
    - psycopg2-binary
