---


- name: ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Download Agave
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Agave.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes

- name: Copy debconf selections file
  template:
    src: console-setup.selections.template
    dest: /tmp/console-setup.selections
    mode: 0644

- name: Set console font non-interactively
  shell: debconf-set-selections < /tmp/console-setup.selections
  register: debconf_set_result
  changed_when: debconf_set_result.stdout != ''

- name: Reconfigure console-setup package non-interactively
  shell: dpkg-reconfigure -f noninteractive console-setup

- name: install spaceship shell
  git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: ~/.zsh/starship

- name: get tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: configure tmux
  template:
    src: tmux.conf.template
    dest: ~/.tmux.conf

- name: set .vimrc
  template:
    src: vimrc.template
    dest: ~/.vimrc

- name: set .zshrc
  template:
    src: zshrc.template
    dest: ~/.zshrc

- name: set up .dotfiles
  file:
    path: ~/.dotfiles
    state: directory

- name: set up custom tools
  copy:
    src: ../tools/record.sh
    dest: ~/.dotfiles/record.sh
    mode: '0777'
