---
- name: upgrade packages
  apt:
    upgrade: dist

- name: install base packages (common)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apache2
    - build-essential
    - curl
    - fontconfig
    - git
    - imagemagick
    - libcurl4-openssl-dev 
    - libffi-dev
    - libfontconfig
    - libfontconfig-dev
    - libncurses5-dev
    - libpq-dev
    - libssl-dev
    - netcat
    - perl
    - python3-dev
    - python3-pip
    - smbclient
    - tmux
    - winbind
    - wine
    - zlib1g-dev
    - zsh

- name: install base packages (debian jessie)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - libapache2-mod-php5
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

- name: install base packages (debian stretch)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - libapache2-mod-php
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'

- name: touch path for gopath
  file:
    path: /opt/go
    state: directory

- name: change shell for root user
  user:
    name: root
    shell: /bin/zsh

- name: add ops user
  user:
    name: '{{ ops_user }}'
    password: '{{ ops_pass }}'
    groups: sudo
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: add ops user to sudoers.d
  lineinfile:
    path: '/etc/sudoers.d/{{ ops_user }}'
    state: present
    create: yes
    regexp: '{{ ops_user }} .*'
    line: '{{ ops_user }} ALL=(ALL) NOPASSWD:ALL'
