---
- name: install gobuster
  raw: /root/.local/opt/go/bin/go install github.com/OJ/gobuster@latest

- name: get dnsrecon
  git:
    repo: https://github.com/darkoperator/dnsrecon
    dest: /opt/dnsrecon
    update: yes

- name: install dnsrecon
  pip:
    requirements: requirements.txt
  args:
    chdir: /opt/dnsrecon

- name: get cloud_unum
  git:
    repo: https://github.com/initstring/cloud_enum.git
    dest: /opt/cloud_enum
    update: yes

- name: install cloud_enum
  pip:
    requirements: requirements.txt
  args:
    chdir: /opt/cloud_enum

- name: install scoutsuite
  pip:
    name: scoutsuite
    executable: pip3

- name: get weirdAAL
  git:
    repo: https://github.com/carnal0wnage/weirdAAL.git
    dest: /opt/weirdAAL
    update: yes

- name: install weirdAAL
  pip:
    requirements: requirements.txt
  args:
    chdir: /opt/weirdAAL

- name: get enum4linux
  git:
    repo: https://github.com/portcullislabs/enum4linux
    dest: /opt/enum4linux
    update: yes

- name: get eyewitness
  git:
    repo: https://github.com/ChrisTruncer/EyeWitness
    dest: /opt/eyewitness
    update: yes

- name: install eyewitness
  shell: ./setup.sh
  args:
    chdir: /opt/eyewitness/Python/setup

- name: get goofile
  git:
    repo: https://github.com/crunchsec/goofile
    dest: /opt/goofile
    update: yes

- name: get rawr
  git:
    repo: https://bitbucket.org/al14s/rawr
    dest: /opt/rawr
    update: yes

- name: install rawr
  shell: ./install.sh y
  args:
    chdir: /opt/rawr

- name: get theharvester
  git:
    repo: https://github.com/laramies/theHarvester
    dest: /opt/theharvester
    update: yes

- name: get wafw00f
  git:
    repo: https://github.com/EnableSecurity/wafw00f
    dest: /opt/wafw00f
    update: yes

- name: install wafw00f
  shell: python3 setup.py install
  args:
    chdir: /opt/wafw00f

- name: get meterssh
  git:
    repo: https://github.com/trustedsec/meterssh
    dest: /opt/meterssh
    update: yes

- name: get pre-req for enum4linux
  get_url:
    url: https://raw.githubusercontent.com/Wh1t3Fox/polenum/master/polenum.py
    dest: /usr/bin/polenum.py
    mode: 0755

- name: get recon-ng
  git:
    repo: https://github.com/lanmaster53/recon-ng.git
    dest: /opt/recon-ng
    update: yes

- name: install recon-ng
  pip:
    requirements: /opt/recon-ng/REQUIREMENTS

- name: install python3 fierce
  pip:
    name: fierce
    executable: pip3

- name: get SIET
  git:
    repo: https://github.com/Sab0tag3d/SIET
    dest: /opt/siet
    update: yes
